app_port: 5000
service:
  workingdir: /home/vagrant/django-project/myproject
  execstart: /home/vagrant/django-project/myvenv/bin/gunicorn --access-logfile - --workers 3 --bind 0.0.0.0:8000 myproject.wsgi:application

app:
  env:
    SQLALCHEMY_DATABASE_URI: mysql://demo:demo@db01/demo
    SQLALCHEMY_TRACK_MODIFICATIONS: False
    SECRET_KEY: sfvgbrh212131