---
deploymentservers:
  hosts:
    deployment1:
      ansible_host: 20.23.242.67
      ansible_port: 22
      ansible_ssh_user: azureuser
  vars:
    ansible_python_interpreter: /usr/bin/python3
database:
  hosts:
    deployment1:
      ansible_host: 20.23.242.67
      ansible_port: 22
      ansible_ssh_user: azureuser
  vars:
    ansible_python_interpreter: /usr/bin/python3
