---
- hosts: database
  become: true
  vars:   
    mysql_root_password: pass123 
  
  tasks:

  - name: Specify MySQL root password before installing
    debconf: 
      name: 'mysql-server' 
      question: 'mysql-server/root_password' 
      value: '{{mysql_root_password | quote}}' 
      vtype: 'password'

  - name: Confirm MySQL root password before installing
    debconf: 
      name: 'mysql-server' 
      question: 'mysql-server/root_password_again'
      value: '{{mysql_root_password | quote}}'
      vtype: 'password'
    
  - name: install mysql-server
    apt: 
      name: mysql-server 
      state: present 
      update_cache: yes

  - name: ensure mysql started
    service:
      name: mysql
      state: started
      enabled: yes

